### ISSUE TITLE
Can I reduce the size of image in the contact page?

### ISSUE THREAD

**Issue by mrsensible** [wowchemy/starter-hugo-research-group#1]
Hi there I am trying to change the image size on the contact page in RStudio.  The path is `starter-research-group/content/contact/image.md`. The image that I am using is too large to fit on the page so I want to reduce the size. Can you help me?

The code is written below:

```
advanced:
  css_class: fullscreen
design:
  background:
    image: east_quadrangle.png
    image_darken: 0
    image_parallax: false
    image_position: center
    image_size: cover   <- "I know that the image size has to be reduced but I don't know any CSS code"
    text_color_light: true
  columns: "1"
  spacing:
    padding:
    - 20px
    - "0"
    - 20px
    - "0"
headless: true
subtitle: null
title: null
weight: 20
widget: blank
```
